title = "Jonathan's Blog"
baseURL = "https://jmezach.github.io"
languageCode = "en-us"
theme = "ananke"
disqusShortname = "jmezach"
enableEmoji = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-108599285-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  body_classes = "helvetica bg-light-gray"
  favicon = ""
  description = "Hello World"
  facebook = ""
  twitter = "https://twitter.com/jmezach"
  instagram = "https://www.instagram.com/jonathanmezach/"
  youtube = "https://www.youtube.com/channel/UCA4OPwB_HlIhSW6EaXOGcJQ"
  github = "https://github.com/jmezach"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jmezach/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  featured_image = "/img/hero-image.jpg"
  recent_posts_number = 6
  show_reading_time = true

[privacy]	
  [privacy.disqus]	
    disable = false	
  [privacy.googleAnalytics]	
    anonymizeIP = true	
    disable = false	
    respectDoNotTrack = true	
    useSessionStorage = true	
  [privacy.instagram]	
    disable = true	
  [privacy.twitter]	
    disable = true	
  [privacy.vimeo]	
    disable = true	
  [privacy.youtube]	
    disable = true 